cmake_minimum_required(VERSION 3.23)
project(ymsummorizer.common VERSION ${CMAKE_PROJECT_VERSION})

find_package(magic_enum REQUIRED)
find_package(Boost REQUIRED)

add_target(${PROJECT_NAME} STATIC
  INCLUDE_PATH
    ${CMAKE_CURRENT_SOURCE_DIR}/include
  SOURCES_PATH 
    ${CMAKE_CURRENT_SOURCE_DIR}/src
  PCH_PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/include/common/common_pch.h
  PCH_PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/src/pch.h
  USES_PUBLIC 
    hare
    magic_enum::magic_enum
    Boost::boost
    $<$<PLATFORM_ID:Windows>:ws2_32>
    $<$<PLATFORM_ID:Windows>:wsock32>
  TEST_SOURCES_PATH 
    ${CMAKE_CURRENT_SOURCE_DIR}/tests
)
