#pragma once

#define YMSUMMORIZER_VERSION_MAJOR 0
#define YMSUMMORIZER_VERSION_MINOR 0
#define YMSUMMORIZER_VERSION_PATCH 1
#define YMSUMMORIZER_VERSION "0.0.1"
#define YMSUMMORIZER_VERSION_GENERATION_TIME "2024-11-19T20:18:15"
